- question: Not the True about some information is
  answers:
    - Disinformation
    - Misinformation
    - Malinformation
  correct_answer: Disinformation

- question: Not the True about some information is
  answers:
    - Disinformation
    - Misinformation
    - Malinformation
  correct_answer: Disinformation

- question: Not the True about some information is
  answers:
    - Disinformation
    - Misinformation
    - Malinformation
  correct_answer: Disinformation

- question: Not the True about some information is
  answers:
    - Disinformation
    - Misinformation
    - Malinformation
  correct_answer: Disinformation