- question: What does the concept of "information hygiene" include?
  answers:
    - The impact on human health and public health of information streams received by a person.
    - A system designed for receiving, processing, storing, displaying, and/or recording data.
    - A new historical phase of societal development.