# App variables
app_name: "Pollster"
app_version: '0.0.7'
app_title: 'Desktop control panel for your quiz app'
app_win_width: 1280
app_win_height: 720
# Font
font_regular:
  family: "Arial"
  size: 14
font_bold:
  family: "Arial"
  size: 14
  weight: "bold"
font_underline:
  family: "Arial"
  size: 14
  underline: true
font_heading:
  family: "Arial"
  size: 16
  weight: "bold"
# UI Colors
color_font: '#fff'
color_background: '#535353'
color_black: '#121212'
color_foreground: '#fff'
color_focus: '#b3b3b3'
color_accent: '#1db954'