en:
  greeting_message: "Hi! My name is Pollster. Let's begin our polls!"
  farewell_message: "Bye! See ya later"
ua:
  greeting_message: "Привіііт! Почнемо роботу!"
  farewell_message: "Прощавай! До зустрічі"